name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725554910:role/GitHubActionsTerraformProject03Role
          aws-region: ap-south-1

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725554910:role/GitHubActionsTerraformProject03Role
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Outputs
        run: |
          echo "VPC ID:"
          terraform output -raw vpc_id
          echo ""

          echo "EC2 Instance ID:"
          terraform output -raw ec2_instance_id
          echo ""

          echo "Elastic IP:"
          terraform output -raw elastic_ip
          echo ""

          echo "Application URL:"
          terraform output -raw application_url
          echo ""

          echo "S3 Bucket Name:"
          terraform output -raw s3_bucket_name

      - name: Validate Application
        run: |
          APP_URL=$(terraform output -raw application_url)
          echo "Checking application at $APP_URL"
          curl --fail --retry 10 --retry-delay 10 "$APP_URL"
